version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: react-app
    depends_on:
      - backend
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev", "--", "--host"]
    stdin_open: true
    tty: true
    networks:
      - mern-network

  backend:
    build: ./backend
    container_name: node-app
    ports:
      - "5000:5000"
    depends_on:
      - database
    env_file:
      - ./backend/.env
    networks:
      - mern-network
  
  database:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge