apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: mern
spec:
  replicas: 2
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
        - name: backend
          image: your-dockerhub-username/mern-backend:1.0.0
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT
            - name: API_BASE_PATH
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: API_BASE_PATH
            - name: MONGODB_URI
              value: "mongodb://root:supersecret@mongo:27017/?authSource=admin"

          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: mern
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
