apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: social-media
spec:
  replicas: 1
  selector:
    matchLabels: { app: frontend }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      containers:
        - name: frontend
          image: gulamgaush/social-media-frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests: { cpu: "50m", memory: "128Mi" }
            limits:   { cpu: "200m", memory: "256Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: social-media
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30007
